### ISSUE TITLE
AndroidRuntimeException: Calling startActivity()

### ISSUE THREAD

**Issue by praveenbbhati** [yx544806988/yin_auto_start#2]
I'm using this version autostart: ^0.0.1

Device -  OnePlus 7 
OS Android 10

`W/System.err(28183): android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
W/System.err(28183): 	at android.app.ContextImpl.startActivity(ContextImpl.java:964)
W/System.err(28183): 	at android.app.ContextImpl.startActivity(ContextImpl.java:940)
W/System.err(28183): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:383)
W/System.err(28183): 	at com.judemanutd.autostarter.AutoStartPermissionHelper.startIntent(AutoStartPermissionHelper.kt:325)
W/System.err(28183): 	at com.judemanutd.autostarter.AutoStartPermissionHelper.autoStartOnePlus(AutoStartPermissionHelper.kt:308)
W/System.err(28183): 	at com.judemanutd.autostarter.AutoStartPermissionHelper.getAutoStartPermission(AutoStartPermissionHelper.kt:118)
W/System.err(28183): 	at com.yin.autostart.AutostartPlugin.onMethodCall(AutostartPlugin.java:53)`

**Comment by ghost** [comment]
i am facing same issue

**Comment by alexi190** [comment]
If any one facing this issue can use my package which is a fork of this repo.
add below line in pubspec.yaml file

```
autostart:
     git:
       url: git://github.com/peswanibros/yin_auto_start.git

**Comment by Bes79** [comment]
hi! this is work for me
